export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const ADD_NEW_USER_DATA_SUCCESS = 'ADD_NEW_USER_DATA_SUCCESS';
export const ADD_NEW_USER_DATA_FAILED = 'ADD_NEW_USER_DATA_FAILED';
export const SEND_EMAIL_VERIFICATION_SUCCESS =
    'SEND_EMAIL_VERIFICATION_SUCCESS';
export const SEND_EMAIL_VERIFICATION_FAILED = 'SEND_EMAIL_VERIFICATION_FAILED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const LOADING = 'LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const ADD_BOOKING = 'ADD_BOOKING';
